Repository optile/checkout-ios, pull requests merged in 2022-08, with the labels that each got.

#232 [PCX-3633] Add providers array in payment services
  .swiftpm/xcode/xcshareddata/xcschemes/PayoneerCheckout.xcscheme
  Package.swift
  Sources/Networking/Model/AccountRegistration.swift
  Sources/Networking/Model/ApplicableNetwork.swift
  Sources/Networking/Model/PresetAccount.swift
  Sources/Payment/PaymentService.swift
  Sources/PaymentServices/ApplePayBraintreePaymentService/ApplePayBraintreePaymentService.swift
  Sources/PaymentServices/BasicPaymentService/BasicPaymentService.swift
  Sources/PayoneerCheckout/Core/ChargePresetService.swift
  Sources/PayoneerCheckout/ListResultProvider/ListResultProvider.swift
  Sources/PayoneerCheckout/PaymentProcess/RequestSender.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Model/Input.Network.swift
  Sources/PayoneerCheckout/UI/Service/PaymentServicesFactory.swift
  Tests/PaymentServicesTests/ApplePayBraintreePaymentServiceTests.swift
  Tests/PaymentServicesTests/BasicPaymentServiceTests.swift
  Tests/PaymentTests/RedirectTests.swift
  Tests/PayoneerCheckoutTests/UI/Scenes/Input/Field/Validation/ValidationTests.swift
  Tests/PayoneerCheckoutTests/UI/Scenes/Input/Model/RegistrationOptionsTests.swift
Labels: enhancement, high priority

#226 [PCX-3638] Optimize Swift code (post Objective-C)
  .swiftpm/xcode/xcshareddata/xcschemes/ApplePayBraintreePaymentService.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/PayoneerCheckout-Package.xcscheme
  ExampleCheckout/UITests/PaymentService/PaymentService.swift
  ExampleCheckout/UITests/PaymentSession/NetworkService.swift
  ExampleCheckout/UITests/PaymentSession/PaymentSessionService.swift
  Sources/Networking/Model/InstallmentsPlan.swift
  Sources/Networking/Operations/SendRequestOperation.swift
  Sources/Networking/Protocols/Connection.swift
  Sources/Networking/URLSessionConnection.swift
  Sources/Payment/PaymentService.swift
  Sources/PaymentServices/ApplePayBraintreePaymentService/ApplePayBraintreePaymentService.swift
  Sources/PaymentServices/BasicPaymentService/BasicPaymentService.swift
  Sources/PayoneerCheckout/Core/ChargePresetService.swift
  Sources/PayoneerCheckout/Extensions/Result+interactionAdvices.swift
  Sources/PayoneerCheckout/Interface/Checkout.swift
  Sources/PayoneerCheckout/Interface/CheckoutAppearance.swift
  Sources/PayoneerCheckout/Interface/CheckoutConfiguration.swift
  Sources/PayoneerCheckout/Interface/CheckoutDefaultFontProvider.swift
  Sources/PayoneerCheckout/Interface/CheckoutResult.swift
  Sources/PayoneerCheckout/PaymentProcess/RequestSender.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/PaymentProcess/Input.ViewController.RequestResultHandler.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/ViewController/Input.ViewController.swift
  Sources/PayoneerCheckout/UI/Scenes/List/PaymentListViewController.RequestResultHandler.swift
  Sources/PayoneerCheckout/UI/Scenes/List/PaymentListViewController.swift
  Tests/NetworkingTests/SendRequestOperationTests.swift
  Tests/PayoneerCheckoutTests/Interface/CheckoutTests.swift
  Tests/PayoneerCheckoutTests/Interface/MockChargePresetService.swift
  Tests/PayoneerCheckoutTests/Mock/MockConnection.swift
  Tests/PayoneerCheckoutTests/Mock/MockDataSource.swift
  Tests/PayoneerCheckoutTests/UI/Service/PaymentSession/PaymentSessionServiceTests.swift
Labels: refactor, maintenance

#231 [PCX-3502] Validate checkbox states
  ExampleCheckout/UITests/ExtraElementsCheckboxTests.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Model/Field/Checkbox/Input.Field.Checkbox.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Model/Field/Checkbox/Input.Field.ExtraElementCheckbox.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Model/Field/Checkbox/Input.Field.RegistrationCheckbox.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Model/ModelTransformer/Input.ModelTransformer.ExtraElementsTransformer.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Table/Cell/Input.Table.CheckboxViewCell.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Table/Input.Table.Controller.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Table/Input.Table.Validator.swift
Labels: enhancement

#234 [PCX-3742] Fix undefined state when example app URL is empty
  ExampleCheckout/Sources/ViewController.swift
  ExampleCheckout/UITests/NavigationTests.swift
Labels: bug

#233 [PCX-3867] Fix text input view expanding bug
  Sources/PayoneerCheckout/UI/Scenes/Input/Table/Cell/Input.Table.TextFieldViewCell.swift
Labels: bug

#235 [PCX-3720] Set version 0.9.0
  ExampleCheckout/ExampleCheckout.xcodeproj/project.pbxproj
  Sources/Networking/Resources/version.json
Labels: release

#237 [PCX-3918] Apple Pay UI tests failing
  ExampleCheckout/UITests/ApplePayBraintreeTests.swift
  ExampleCheckout/UITests/CardTests.swift
Labels: bug

#240 [PCX-3036] Fix pull to refresh
  Sources/PayoneerCheckout/UI/Scenes/List/Table/List.Table.Controller.swift
Labels: bug
