Repository optile/checkout-ios, pull requests merged in 2022-07, with the labels that each got.

#224 [PCX-3270] Add pull request template
  .github/pull_request_template.md
Labels: maintenance

#225 [PCX-3383] Display checkboxes for ExtraElements
  ExampleCheckout/ExampleCheckout.xcodeproj/project.pbxproj
  ExampleCheckout/UITests/Abstract/NetworksTests.swift
  ExampleCheckout/UITests/ExtraElementsCheckboxTests.swift
  ExampleCheckout/UITests/ExtraElementsTests.swift
  ExampleCheckout/UITests/PaymentSession/Model/CheckoutConfiguration.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Model/Field/Input.Field.Identifier.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Model/ModelTransformer/Input.ModelTransformer.ExtraElementsTransformer.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Model/ModelTransformer/Input.ModelTransformer.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Table/Cell/Input.Table.CheckboxViewCell.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Table/Cell/Input.Table.TextFieldViewCell.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Table/Input.Table.LayoutController.swift
Labels: feature

#228 [PCX-3597] Submit checkbox states to OPG
  Sources/Networking/Model/OperationData.swift
  Sources/Networking/Requests/NetworkRequest.Operation.swift
  Sources/Payment/Model/Form.swift
  Sources/PaymentServices/ApplePayBraintreePaymentService/NetworkRequestBuilder.swift
  Sources/PaymentServices/BasicPaymentService/NetworkRequestBuilder.swift
  Sources/PayoneerCheckout/PaymentProcess/RequestSender.swift
  Tests/NetworkingTests/OperationTests.swift
  Tests/PayoneerCheckoutTests/PaymentProcess/PaymentRequestBuilderTests.swift
  Tests/PayoneerCheckoutTests/Resources/ListResultWithExtraElements.json
Labels: enhancement

#227 [PCX-3652] Update primary color
  ExampleCheckout/ExampleCheckout.xcodeproj/project.pbxproj
  ExampleCheckout/Sources/CustomFontProvider.swift
  ExampleCheckout/Sources/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  ExampleCheckout/Sources/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ExampleCheckout/Sources/Resources/Assets.xcassets/Contents.json
  ExampleCheckout/Sources/Resources/Assets.xcassets/CustomAccentColor.colorset/Contents.json
  ExampleCheckout/Sources/Resources/Info.plist
  ExampleCheckout/Sources/Resources/RobotoCondensed-Bold.ttf
  ExampleCheckout/Sources/Resources/RobotoCondensed-Regular.ttf
  ExampleCheckout/Sources/Rubik-Bold.ttf
  ExampleCheckout/Sources/Rubik-Regular.ttf
  ExampleCheckout/Sources/ViewController.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Table/Cell/Input.Table.CheckboxViewCell.swift
  docs/card.png
  docs/list.png
  docs/sepa.png
Labels: enhancement

#229 [PCX-3451] Add data model unit tests
  Sources/Networking/CustomErrorInfo.swift
  Sources/Networking/Model/Checkbox.swift
  Sources/Networking/Model/DeregistrationData.swift
  Sources/Networking/Model/ErrorInfo.swift
  Sources/Networking/Model/InputElement.swift
  Sources/Networking/Model/Interaction.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Model/ModelTransformer/Input.ModelTransformer.ExtraElementsTransformer.swift
  Sources/PayoneerCheckout/UI/Scenes/Input/Protocols/DefinesKeyboardStyle.swift
  Tests/NetworkingTests/Models/CustomErrorInfoTests.swift
  Tests/NetworkingTests/Models/ErrorInfoTests.swift
  Tests/NetworkingTests/Models/InteractionTests.swift
  Tests/NetworkingTests/Models/ParameterTests.swift
  Tests/NetworkingTests/Models/ProviderParametersTests.swift
Labels: maintenance
